### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by szklo** [jeppevinkel/jellyfin-tizen-builds#38] opened 2024-05-16 17:21 UTC
after installing jellyfin from 2024/05/13 it does not run, the message is as in the picture.
![jellyfin](https://github.com/jeppevinkel/jellyfin-tizen-builds/assets/98661534/697f8b12-ec7d-4639-8926-98b642f14802)

**Comment by RoberHook** [comment] 2024-05-16 20:02
Hello. I get the same error. 
I have installed **Jellyfin.wgt** and **Jellyfin-TrueHD.wgt** with identical results.

**Comment by szklo** [comment] 2024-05-17 18:41
Let me know how you solve this problem

**Comment by RoberHook** [comment] 2024-05-17 19:52
Finally I have reinstalled the version Jellyfin.wgt 10.8.13 published on 2023-29-11 that I had saved and which has a weight of 42.6 MB.
I have noticed that the weight of version 10.8.13 was maintained over time until the date 2024-04-28 18:04. On that same date and time 2024-04-28 18:54, the weight of the file became 9.15 MB.... how is that possible?!
And the new version 10.9.1 has a weight of 10.2 MB
Is it possible that the file was obtained after a compilation that did not take into account necessary components?

**Comment by jeppevinkel** [comment] 2024-05-17 20:38
> Finally I have reinstalled the version Jellyfin.wgt 10.8.13 published on 2023-29-11 that I had saved and which has a weight of 42.6 MB. I have noticed that the weight of version 10.8.13 was maintained over time until the date 2024-04-28 18:04. On that same date and time 2024-04-28 18:54, the weight of the file became 9.15 MB.... how is that possible?! And the new version 10.9.1 has a weight of 10.2 MB Is it possible that the file was obtained after a compilation that did not take into account necessary components?

The file size is supposed to be small. The large ones are large because they have a bunch of extra fonts that aren't used on the TV. This size reduction is intentional and documented on [jellyfin-tizen readme](https://github.com/jellyfin/jellyfin-tizen/?tab=readme-ov-file#build-jellyfin-web). It's caused by `USE_SYSTEM_FONTS=1`.

**Comment by RoberHook** [comment] 2024-05-18 09:14
I understand. So today I will try to test version 10.8.13 from 2024-05-04 11:37 which I understand is the result of font reduction only and therefore in my case it should work correctly.
Then I will also try the new version recently published 2024-05-18 01:42 10.9.2 and I will comment on how it turned out for me.
Thank you.

**Comment by RoberHook** [comment] 2024-05-18 09:21
@jeppevinkel   Sorry, I clicked the wrong option and opened a new item. I have tried to delete it but I couldn't do it. Can you delete it?

**Comment by jeppevinkel** [comment] 2024-05-18 09:32
> @jeppevinkel Sorry, I clicked the wrong option and opened a new item. I have tried to delete it but I couldn't do it. Can you delete it?

No worries, I have deleted it. I can't get any of the releases from 10.9.0 and newer to work on my TV, so those might not work.

**Comment by szklo** [comment] 2024-05-18 13:40
The latest version works fine.
Many thanks to the author.

**Comment by szklo** [comment] 2024-05-18 13:44
A new, more stable version for Android would be useful.

**Comment by omegaweapon1978** [comment] 2024-05-19 08:09
hi, thanx 4 your work. any 10.9.x version i try to install give me the same attached issue (just time diplayed and no login screen), there's a way to fix? thanks.
![tv](https://github.com/jeppevinkel/jellyfin-tizen-builds/assets/73910962/11d4bb9f-6c9a-4e31-a83b-a322b88b6f7e)

**Comment by Tntdruid** [comment] 2024-05-19 08:34
Did you update the server too?

**Comment by omegaweapon1978** [comment] 2024-05-19 08:41
Yes, latest version

**Comment by jeppevinkel** [comment] 2024-05-19 12:57
> hi, thanx 4 your work. any 10.9.x version i try to install give me the same attached issue (just time diplayed and no login screen), there's a way to fix? thanks. ps: jellyfin server is updated ![tv](https://private-user-images.githubusercontent.com/73910962/331856814-11d4bb9f-6c9a-4e31-a83b-a322b88b6f7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjM2ODQsIm5iZiI6MTcxNjEyMzM4NCwicGF0aCI6Ii83MzkxMDk2Mi8zMzE4NTY4MTQtMTFkNGJiOWYtNmM5YS00ZTMxLWE4M2ItYTMyMmI4OGI2ZjdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyNTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNmMwMDk0Nzc1MDRmNTA1MGRkMTY3ODkwZGI0OGNiNGM4NWI5YmU0MDIzZDMxMTU4MmQ4NWM4OWNkMjg0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9PJFSfNkfQTZojJxmwSPvvSs_XPCi9rDRdMzYZtKq4)

I currently get a very similar result. Some people have had success with 10.9.z, so I think the difference in who it works for might be up to TV firmware or software version.

**Comment by CLEMENTINATOR** [comment] 2024-05-20 04:59
Has been fixed in https://github.com/jellyfin/jellyfin-web/pull/5558, so we just need to rebuild

**Comment by jeppevinkel** [comment] 2024-05-20 16:49
> Has been fixed in [jellyfin/jellyfin-web#5558](https://github.com/jellyfin/jellyfin-web/pull/5558), so we just need to rebuild

I’m not home to test it, but the Jellyfin-prerelease version of the new build should include that fix.

**Comment by CLEMENTINATOR** [comment] 2024-05-21 05:10
I just tested the jellyfin-prerelease of the new build. Good news, the issue is not here anymore but i end up on an infinite loop after signing in
![image](https://github.com/jeppevinkel/jellyfin-tizen-builds/assets/724253/fd8c163f-135d-4557-b5ac-3f1d9fb7aa1e)

**Comment by jeppevinkel** [comment] 2024-05-21 16:18
I've never used quick connect, so I don't know about that, but I tested normal login to at least work on my TV using this prerelease now. I may need to rethink my builds though and see if I can maybe target branches for specific jellyfin version rather than just the master branch. It seems some fixes go directly to the 10.9.z branch without first being in the master branch.

**Comment by jeppevinkel** [comment] 2024-05-23 17:40
Since the main problem from this issue seems to be fixed with the most recent builds, I'll close this now.

**Closed by jeppevinkel** 2024-05-23 17:40 UTC
