### ISSUE TITLE
Invalid certificate chain with certificate in signature

### ISSUE THREAD

**Issue by calebadcock** [jeppevinkel/jellyfin-tizen-builds#39] opened 2024-05-17 23:56 UTC
I'm using docker to install via [Georift/install-jellyfin-tizen](https://github.com/Georift/install-jellyfin-tizen)

```
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
```

I've tried other build versions going back to [2023-11-29](https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2023-11-29)

TV Model: `QN65LS03DAFXZA`

**Comment by jeppevinkel** [comment] 2024-05-18 01:42
I haven't encountered this issue before, but I see that others have https://github.com/Georift/install-jellyfin-tizen/issues/21 I do wonder what the cause could be though. It might relate to specific TV firmware or Tizen versions since I can't replicate this issue on my TV.

**Comment by kalua85** [comment] 2024-05-22 16:45
Same issue here:

```
PS C:\tizen-studio\tools\ide\bin> .\tizen.bat install -n .\Jellyfin.wgt -t QE65S95DATXXN
Transferring the package...
Transferred the package: C:\tizen-studio\tools\ide\bin\Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[9]
app_id[AprZAARz4r.Jellyfin] installing[19]
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [3810]ms
Failed to install Tizen application.
Total time: 00:00:07.885
```

**Comment by jeppevinkel** [comment] 2024-05-23 17:41
I can't reproduce with issue on my TV, so I'm at a loss for how to help

**Comment by kalua85** [comment] 2024-05-25 07:48
Created my own samsung certificate and added my DUID to it and then building manually, installation worked without issue. So I guess this can be closed as I don't see how this can be automated.

**Comment by 0x414c49** [comment] 2024-06-07 12:32
I don't know why it happens, this is the 2nd time. I have to remove the app and install it manually again

**Comment by jeppevinkel** [comment] 2024-06-10 16:04
I'll close this since I don't know of a way to programmatically create a general Samsung certificate. This is unsolvable for now. It might be Samsung adding more restrictions on distribution outside their store.

**Closed by jeppevinkel** 2024-06-10 16:04 UTC

**Comment by testuser7** [comment] 2024-11-18 17:58
@jeppevinkel Here's how to manually create certificates: https://gist.github.com/andreas-mausch/026413d908ba61cda15981bb4fbcd276
But I'm getting the same error `Invalid certificate chain with certificate in signature.`
What CA is used for certificates generated from IDE?

**Comment by testuser7** [comment] 2024-11-20 07:54
I can successfully generate certificates. Updated instructions here: https://gist.github.com/andreas-mausch/026413d908ba61cda15981bb4fbcd276
